inherit: true

build:
  environment:
    php: 8.2.22
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

tools:
    php_code_sniffer: true
    php_cpd: false
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    excluded_paths:
        - lib/*
        - tests/*

build_failure_conditions:
    - 'elements.rating(<= F).new.exists'
    - 'issues.severity(>= MAJOR).new.exists'
