-- MySQL dump 10.13  Distrib 5.5.40, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: production
-- ------------------------------------------------------
-- Server version	5.5.40-0ubuntu0.12.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `emailtemplate`
--

INSERT INTO `emailtemplate` VALUES (1,'Created!','Many thanks for your interest in joining Wikipedia. I\'ve gone ahead and created the account for you. You will receive a separate automated e-mail from wiki@wikimedia.org with your login credentials. You can use these to log in for the first time, when you will be prompted to create a new password.\r\n\r\nWhen you have successfully logged in, you may find the &quot;getting started&quot; section of our help pages useful (http://en.wikipedia.org/wiki/Help:Contents/Getting_started). Of particular interest may be the introduction to Wikipedia (http://en.wikipedia.org/wiki/Wikipedia:Introduction) which has some information to help you get up to speed with the way things work on the encyclopedia.\r\n\r\nOne useful hint: when you have logged in for the first time and created your own password, go to your preferences (the link for them is right at the top of the screen), and ensure your email address is set where indicated. Should you forget your password, then this will allow you to have a new one sent to you!\r\n\r\nI wish you all the best and hope you enjoy your time on Wikipedia.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','Are you sure that you want to create? Please ensure you have completed all the checks.',1,1,0);
INSERT INTO `emailtemplate` VALUES (2,'Too Similar','Many thanks for your interest in joining Wikipedia. Unfortunately the username that you have requested is too similar to an active account, which may make it difficult for other contributors to distinguish you from the other user.\r\n\r\nPlease take a look at our username policy (http://en.wikipedia.org/wiki/Wikipedia:Username_policy) and choose a different username. You may be able to create the account with the new name you have chosen yourself at http://en.wikipedia.org/w/index.php?title=Special:Userlogin&amp;type=signup. If so, I wish you all the best and hope you enjoy your time on Wikipedia.\r\n\r\nIf you are still unable to create the name yourself, we will gladly process your new request here, and I look forward to hearing from you again with your new choice of username.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','This action will send an email to the user. Are you sure that there is a conflict?',0,1,0);
INSERT INTO `emailtemplate` VALUES (3,'Taken','Many thanks for your interest in joining Wikipedia.  Unfortunately the username that you have requested is already taken.  Please choose another username (unless you had created the account yourself after requesting it).  After you have chosen another username, you may be able to create the account with the new name you have chosen yourself at http://en.wikipedia.org/w/index.php?title=Special:Userlogin&amp;type=signup. If so, I wish you all the best and hope you enjoy your time on Wikipedia. If you are still unable to create the account yourself, we will gladly process your new request here, so feel free to submit another request.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','his action will send an email to the user. Have you checked that the account is already taken?',0,1,0);
INSERT INTO `emailtemplate` VALUES (4,'UPolicy','Many thanks for your interest in joining Wikipedia. Unfortunately the username that you have requested does not comply with our username policy, and so I am unable to create this account for you.\r\n\r\nPlease take a look at our username policy (http://en.wikipedia.org/wiki/Wikipedia:Username_policy) and choose a different username. You may be able to create the account with the new name you have chosen yourself at http://en.wikipedia.org/w/index.php?title=Special:Userlogin&amp;type=signup. If so, I wish you all the best and hope you enjoy your time on Wikipedia.\r\n\r\nIf you are still unable to create the name yourself, we will gladly process your new request here, and I look forward to hearing from you again with your new choice of username.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','This action will send an email to the user. Are you sure that this request is a violation? Please read [[WP:UPOL]] completely before deciding.',0,1,0);
INSERT INTO `emailtemplate` VALUES (5,'Invalid','Many thanks for your interest in joining Wikipedia. Unfortunately we are unable to process your request due to technical restrictions on usernames.\r\n\r\nPlease bear in mind that it is not possible to create usernames containing any of the characters # / | [ ] { } < > @ % : , consisting only of numbers, or ending with an underscore ( _ ) or a space, that have the same character repeating more than 10 times in a row, or are longer than 40 characters.\r\n\r\nPlease choose a username which is within these restrictions and then you can create an account by visiting http://en.wikipedia.org/wiki/Special:UserLogin/signup\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','This action will send an email to the user. Are you sure that the requested username is invalid?',0,1,0);
INSERT INTO `emailtemplate` VALUES (6,'SUL Taken','Many thanks for your interest in joining Wikipedia.  Unfortunately the username that you have requested is already a part of a single user login (SUL) account, meaning that someone else has reserved that name through another one of our websites.\r\n\r\nPlease choose another username (unless you had created the account yourself after requesting it), or look at http://meta.wikimedia.org/wiki/Help:Unified_login for more information on SUL.  After you have chosen another username, you may be able to create the account yourself at http://en.wikipedia.org/w/index.php?title=Special:Userlogin&amp;type=signup. If so, I wish you all the best and hope you enjoy your time on Wikipedia. If you are still unable to create the account yourself, we will gladly process your new request here, so feel free to submit another request.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','This action will send an email to the user. Have you checked that the account is already taken?',0,1,0);
INSERT INTO `emailtemplate` VALUES (7,'Password Reset','Thank you for your interest in joining the English Wikipedia. At this time, we have not created your account as there are similar usernames that already exist on Wikipedia.\r\n\r\nWe have sent password reset emails to them in case you may have forgotten your password. If you do not receive any emails with a temporary password reset, it is possible that you do not own these accounts.\r\n\r\nIf that is so, please email us back and let us know.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','This action will send an email to the user. Are you sure that the requester owned the original reset account?',0,1,0);
INSERT INTO `emailtemplate` VALUES (8,'Open Proxy','Hello and thank you for your interest in joining Wikipedia.\r\n\r\nLooking at our logs, it appears the IP address you\'re requesting from belongs to a proxy or web hosting service. Open or anonymising proxies, including web hosts, are blocked from editing Wikipedia. While this may affect legitimate users, they are not the intended targets. No restrictions are placed on reading Wikipedia through an open or anonymous proxy.\r\n\r\nAlthough Wikipedia encourages anyone in the world to contribute, open proxies are often used abusively. MediaWiki, the wiki software that powers Wikipedia, depends on IP addresses for administrator intervention against abuse, especially by anonymous users. Open proxies allow malicious users to rapidly change IP addresses, causing continuous disruption that cannot be stopped by administrators. Several such attacks have occurred on Wikimedia projects.\r\n\r\nUnfortunately, you won\'t be able to edit while using this open proxy.\r\n\r\nIf you use a different IP address you may be able to create the account yourself at http://en.wikipedia.org/w/index.php?title=Special:Userlogin&type=signup. If so, I wish you all the best and hope you enjoy your time on Wikipedia. If you are still unable to create the account yourself, we will gladly process your new request here, and I look forward to hearing from you again.','Are you certain that this IP address is an open proxy? Being blocked as an open proxy is not sufficient evidence. If in doubt, defer to proxy check.',0,1,0);
INSERT INTO `emailtemplate` VALUES (9,'Notable Person','Hello and thank you for your interest in joining Wikipedia.\r\n     \r\nUnfortunately, we cannot fulfill your account request at this time. To help protect the identities of famous people, requests for usernames matching the real name of a living, notable person must first be verified before they are acted upon. You are welcome to use your real name, but you will need to prove you are who you say you are. You can do this by sending an e-mail to info-en@wikimedia.org and talking with our volunteers there. To ensure that this request is handled correctly, please forward this email to them, as well as provide some form of official documentation proving your identity. This will allow the volunteers there to effectively communicate with us regarding this request. Be aware that e-mails are handled by a volunteer response team, and an immediate reply is not always possible. If the request sits for over a week, feel free to reply to this message and let us know it is taking a while, and we will try and speed up the process for you.\r\n     \r\nIf this is not your name, you will need to edit under a different username, you may be able to create the account with the new username you have chosen yourself at https://en.wikipedia.org/wiki/Special:UserLogin/signup. If so, I wish you all the best and hope you enjoy your time on Wikipedia. If you are still unable to create the username yourself, we will gladly process your new request here.','Are you certain that the username resembles a notable person that is alive?',0,1,0);
INSERT INTO `emailtemplate` VALUES (10,'Shared Username','Many thanks for your interest in joining the English Wikipedia. Unfortunately the username that you requested does not comply with our username policy. I am unable to create the account your requested because it implies that more than one person may use the account. Wikipedia\'s policy is that a user account should be used only by one person and that one person should use only one account in most cases. \r\n\r\nPlease read Wikipedia\'s username policy at http://en.wikipedia.org/wiki/Wikipedia:UPOL#Usernames_implying_shared_use and http://en.wikipedia.org/wiki/Wikipedia:UPOL#Promotional_names. You will have to choose a different username. You may be able to create the account with a new name you have chosen yourself by going to http://en.wikipedia.org/w/index.php?title=Special:Userlogin&amp;type=signup. You can see what usernames are available at http://en.wikipedia.org/wiki/Special:ListUsers. Enter the username you chose at \"Display users starting at:\" and click Go. If you are able to create your account, great and I wish you all the best and hope you enjoy your stay at Wikipedia. If you are unable to create the account yourself, we will gladly process your request here. Make a new request at http://en.wikipedia.org/wiki/Wikipedia:ACC. \r\n\r\nPlease also familiarize yourself with some other Wikipedia policies before you begin contributing to Wikipedia. See http://en.wikipedia.org/wiki/Wikipedia:PROMOTION and http://en.wikipedia.org/wiki/Wikipedia:COI for more information. You may find the advice in http://en.wikipedia.org/wiki/Wikipedia:COISIMPLE helpful.','Are you sure the username implies shared use?',0,1,0);
INSERT INTO `emailtemplate` VALUES (11,'Long response time','Many thanks for your interest in joining Wikipedia. I\'ve gone ahead and created the account for you. You will receive a separate automated e-mail from wiki@wikimedia.org with your login credentials.  Use them to log in for the first time.  You will then be prompted to create a new password.  After you create your own password, I suggest that you go to your preferences (the link for them is right at the top of the screen) and ensure your email address is set where indicated.  If you forget your password, this will allow you to have a new one sent to you.\r\n\r\nPlease accept my apology for how long it took to approve your account.  A combination of software updates, too few volunteers, some extra checks that were needed and an unusually large number of requests contributed to the long delay.\r\n\r\nI wish you all the best and hope you enjoy your time on Wikipedia.','Did this request take an unusually long time to create due to requring CheckUser attention, a long backlog, etc.?',1,1,0);
INSERT INTO `emailtemplate` VALUES (12,'COI risk','Many thanks for your interest in joining Wikipedia. I\'ve gone ahead and created the account for you. You will receive a separate automated e-mail from wiki@wikimedia.org with your login credentials. You can use these to log in for the first time, when you will be prompted to create a new password.\r\n\r\nWhen you have successfully logged in, you may find the \"getting started\" section of our help pages useful <https://en.wikipedia.org/wiki/Help:Contents/Getting_started>. Of particular interest may be the introduction to Wikipedia <https://en.wikipedia.org/wiki/Wikipedia:Introduction> which has some information to help you get up to speed with the way things work on the encyclopedia.\r\n\r\nSince it appears that you may have ties to a business or have ties to/are a famous person, I would like to take a moment to remind you that Wikipedia is not to be used for promotional purposes.  Before editing, please read Wikipedia\'s \"Best Practices for Editors With Close Associations\" at <https://en.wikipedia.org/wiki/Wikipedia:BPCA>, the \"Plain and Simple Conflict of Interest Guide\" at <https://en.wikipedia.org/wiki/Wikipedia:PSCOI>, and Wikipedia\'s policies on promotion at <https://en.wikipedia.org/wiki/Wikipedia:PROMOTION>.  Understanding these policies will help prevent misunderstandings between you and Wikipedia\'s administrators.\r\n\r\nOne useful hint: when you have logged in for the first time and created your own password, go to your preferences (the link for them is right at the top of the screen), and ensure your email address is set where indicated. Should you forget your password, then this will allow you to have a new one sent to you!\r\n\r\nI wish you all the best and hope you enjoy your time on Wikipedia.\r\n\r\n*If you did not make this request, please ignore this email. If you wish to report this, please send an email to accounts-enwiki-l@lists.wikimedia.org with a copy of the original email.*','This email is just like the standard Created email, but including links to WP:BPCA, WP:PSCOI, and WP:PROMOTION.  It is intended to be used for accounts that were created but you suspect that the requester has ties to a company or other entity and may present a COI risk (for example, user used a corporate email address in their account request).  Is this the template you wish to use?',1,1,0);
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2014-11-21 19:28:47
