<!-- tpl:zoom-parts/ip-links.tpl -->
<a id="IPTalk-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/wiki/User_talk:{$ipaddress}" OnClick="$('#IPTalk-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Talk page</a>
<a id="IPLocalContribs-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/wiki/Special:Contributions/{$ipaddress}" OnClick="$('#IPLocalContribs-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Local Contributions</a>
<a id="IPDelEdits-{$index}" class="btn btn-small" target="_blank" href="{$tsurl}/redir.php?tool=tparis-pcount&amp;data={$ipaddress}" OnClick="$('#IPDelEdits-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Deleted Edits</a>
<a id="IPGlobalContribs-{$index}" class="btn btn-small" target="_blank" href="{$tsurl}/redir.php?tool=luxo-contributions&amp;data={$ipaddress}" OnClick="$('#IPGlobalContribs-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Global Contributions</a>
<a id="IPLocalBlockLog-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/w/index.php?title=Special:Log&amp;type=block&amp;page={$ipaddress}" OnClick="$('#IPLocalBlockLog-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Local Block Log</a>
<a id="IPActiveLocalBlock-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/wiki/Special:BlockList/{$ipaddress}" OnClick="$('#IPActiveLocalBlock-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Active Local Blocks</a>
<a id="IPGlobalBlockLog-{$index}" class="btn btn-small" target="_blank" href="https://meta.wikimedia.org/w/index.php?title=Special:Log&amp;type=gblblock&amp;page={$ipaddress}" OnClick="$('#IPGlobalBlockLog-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Global Block Log</a>
<a id="IPActiveGlobalBlock-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/wiki/Special:GlobalBlockList/{$ipaddress}" OnClick="$('#IPActiveGlobalBlock-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Active Global Blocks</a>
<a id="IPWhois-{$index}" class="btn btn-small" target="_blank" href="{$tsurl}/redir.php?tool=oq-whois&amp;data={$ipaddress}" OnClick="$('#IPWhois-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Whois</a>
<a id="IPAbuseLog-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/w/index.php?title=Special:AbuseLog&amp;wpSearchUser={$ipaddress}" OnClick="$('#IPAbuseLog-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">Abuse Filter Log</a>
{if $ischeckuser == true}
  <a id="IPCU-{$index}" class="btn btn-small" target="_blank" href="https://en.wikipedia.org/w/index.php?title=Special:CheckUser&amp;ip={$ipaddress}&amp;reason=%5B%5BWP:ACC%5D%5D%20request%20%23{$id}" OnClick="$('#IPCU-{$index}').css('background-image', 'linear-gradient(to bottom, rgb(0, 255, 0), rgb(0, 230, 0))');">CheckUser</a>
{/if}
<!-- /tpl:zoom-parts/ip-links.tpl -->
