 CREATE TABLE `acc_rev` (
`rev_id` MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`rev_msg` TINYINT NOT NULL ,
`rev_user` TEXT NOT NULL ,
`rev_text` LONGBLOB NOT NULL ,
`rev_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)