DROP TABLE `acc_rev`;
CREATE TABLE `acc_rev` (
`rev_id` MEDIUMINT NULL AUTO_INCREMENT PRIMARY KEY ,
`rev_msg` TINYINT NOT NULL ,
`rev_user` TEXT NOT NULL ,
`rev_text` LONGTEXT NOT NULL ,
`rev_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
